name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment to run the job

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use the version of Python you need

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install -r requirements.txt  # Install dependencies

    # Step 4: Run the tests using unittest
    - name: Run tests
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python -m unittest discover tests/  # Run the tests in the tests/ folder
